name: Deploy AuthService to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    # --- Revisión de código ---
    - name: Code analysis
      run: dotnet build --configuration Release /warnaserror

    # --- Ejecutar tests ---
    - name: Run tests
      run: dotnet test AuthService.Test --configuration Release --no-build --verbosity normal

    # --- Construcción de imagen Docker ---
    - name: Build Docker image
      run: docker build -t authservice:latest .

    - name: Save Docker image
      run: docker save authservice:latest | gzip > authservice.tar.gz

    - name: Copy image to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "authservice.tar.gz"
        target: "/home/ec2-user/"

    - name: Load and run container on EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo systemctl enable docker
          sudo systemctl start docker
          sudo usermod -aG docker ec2-user

          docker load < /home/ec2-user/authservice.tar.gz
          docker stop authservice || true
          docker rm authservice || true
          docker run -d --restart always --name authservice -p 5000:5000 \
            -e CONN="${{ secrets.CONN }}" \
            -e CORS_HOST="${{ secrets.CORS_HOST }}" \
            -e CORS_NAME="${{ secrets.CORS_NAME }}" \
            -e JWT_AUDIENCE="${{ secrets.JWT_AUDIENCE }}" \
            -e JWT_ISSUER="${{ secrets.JWT_ISSUER }}" \
            -e JWT_KEY="${{ secrets.JWT_KEY }}" \
            -e ASPNETCORE_URLS="http://+:5000" \
            authservice:latest