name: Deploy AuthService to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest   # GitHub usa Ubuntu para correr el pipeline

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      # Descarga tu código del repo

    - name: Build Docker image
      run: docker build -t authservice:latest .
      # Construye la imagen Docker con tu Dockerfile

    - name: Save Docker image
      run: docker save authservice:latest | gzip > authservice.tar.gz
      # Empaqueta la imagen en un archivo .tar.gz

    - name: Copy image to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}       # IP pública de tu instancia
        username: ec2-user                  # Usuario correcto en Amazon Linux
        key: ${{ secrets.EC2_SSH_KEY }}     # Llave privada .pem guardada como secreto
        source: "authservice.tar.gz"
        target: "/home/ec2-user/"
      # Copia la imagen comprimida a tu instancia

    - name: Load and run container on EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Asegura que Docker esté activo
          sudo systemctl enable docker
          sudo systemctl start docker

          # Da permisos a ec2-user para usar Docker
          sudo usermod -aG docker ec2-user

          # Aplica el grupo sin reiniciar sesión
          newgrp docker <<EONG
          docker load < /home/ec2-user/authservice.tar.gz
          docker stop authservice || true
          docker rm authservice || true
          docker run -d --name authservice -p 5000:5000 \
            -e CONN=${{ secrets.CONN }} \
            -e CORS_HOST=${{ secrets.CORS_HOST }} \
            -e CORS_NAME=${{ secrets.CORS_NAME }} \
            -e JWT_AUDIENCE=${{ secrets.JWT_AUDIENCE }} \
            -e JWT_ISSUER=${{ secrets.JWT_ISSUER }} \
            -e JWT_KEY=${{ secrets.JWT_KEY }} \
            -e ASPNETCORE_URLS=http://+:5000 \
            authservice:latest
          EONG